version: '3.8'

services:
  gmlimoservices:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmlimoservices-next
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
