/**
 * lib/services/interfaces/IBookingService.ts
 *
 * S — Single Responsibility: Coordinates booking creation, passenger account linking,
 *     confirmation code generation, and async notification dispatch.
 */

import type { Booking, CreateBookingData } from '@/lib/repositories';

export interface SubmitBookingInput extends Omit<CreateBookingData, 'confirmationNumber'> {
  // confirmationNumber is auto-generated by the service
}

export interface SubmitBookingResult {
  success: boolean;
  confirmationNumber?: string;
  booking?: Booking;
  message?: string;
  error?: string;
}

export interface IBookingService {
  submitBooking(input: SubmitBookingInput): Promise<SubmitBookingResult>;
}
