-- CreateTable
CREATE TABLE `about_content` (
    `id` VARCHAR(191) NOT NULL DEFAULT 'default',
    `heroTag` VARCHAR(191) NOT NULL DEFAULT 'PROVEN EXCELLENCE IN BOSTON',
    `heroTitle` VARCHAR(191) NOT NULL DEFAULT 'About GM Limo Services',
    `heroDesc` TEXT NULL,
    `whoTag` VARCHAR(191) NOT NULL DEFAULT 'OUR STORY & VISION',
    `whoTitlePrefix` VARCHAR(191) NOT NULL DEFAULT '10+ Years of',
    `whoTitleHighlight` VARCHAR(191) NOT NULL DEFAULT 'Uncompromising Quality',
    `whoDesc` TEXT NULL,
    `whoText1` TEXT NULL,
    `whoText2` TEXT NULL,
    `whoImage` VARCHAR(191) NULL,
    `featureBoxes` TEXT NULL,
    `pillarsTag` VARCHAR(191) NOT NULL DEFAULT 'SERVICE COMMITMENT',
    `pillarsTitle` VARCHAR(191) NOT NULL DEFAULT 'The GM Luxury Standard',
    `pillarsDesc` TEXT NULL,
    `pillars` TEXT NULL,
    `statsTag` VARCHAR(191) NOT NULL DEFAULT 'MILESTONES OF SUCCESS',
    `statsHeader` VARCHAR(191) NOT NULL DEFAULT 'Trusted By Executives & Travelers Nationwide',
    `statsImage` VARCHAR(191) NULL,
    `stats` TEXT NULL,
    `cta1Tag` VARCHAR(191) NOT NULL DEFAULT 'INDIVIDUAL & FAMILY TRAVEL',
    `cta1Title` VARCHAR(191) NOT NULL DEFAULT 'Reserve Your Private Executive Chauffeur',
    `cta1BtnText` VARCHAR(191) NOT NULL DEFAULT 'Book Online Now',
    `cta1BtnLink` VARCHAR(191) NOT NULL DEFAULT '/book',
    `cta1Image` VARCHAR(191) NULL,
    `cta2Tag` VARCHAR(191) NOT NULL DEFAULT 'CORPORATE ACCOUNTS',
    `cta2Title` VARCHAR(191) NOT NULL DEFAULT 'Need Custom Billing or Fleet Dispatch?',
    `cta2BtnText` VARCHAR(191) NOT NULL DEFAULT 'Contact Corporate Team',
    `cta2BtnLink` VARCHAR(191) NOT NULL DEFAULT '/contact',
    `cta2Image` VARCHAR(191) NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
